<a href="https://colab.research.google.com/github/vikash2006-dot/Python/blob/main/Lec5_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# selecting elements of matrix
a=np.random.randint(1,90,25);

# Giving dim to matrix
b=a.reshape((5,5))
print (b)

# row wise mean of matrix
print(f"mean of all rows {b.mean(axis=1)}")

# column wise mean of matrix
print(f"mean of all columns {b.mean(axis=0)}")

# replacing all even numbers with -1
print(" replacing even number with -1 ............")
b=np.where(b%2==0,-1,b)

# row wise sorting matrix
print("row wise sorting matrix .............")
print(np.sort(b,axis=0))

# column wise sorting matrix
print("column wise sorting matrix ...............")
print(np.sort(b,axis=1))

# row wise sum of matrix
print("row wise sum of matrix ..................")
print(b.sum(axis=1))

# column wise sum of matrix
print("column wise sum of matrix ................")
print(b.sum(axis=0))

# counting -1 column wise
print("counting -1 column wise ................")
cnt=np.sum(b== -1,axis=0)
print(cnt)
# method 2
print("method 2........")
cnt1=np.sum(np.where(b<0,1,0),axis=0)
print(cnt1)


[[ 4 10 52 77 83]
 [60 21 77 67  8]
 [43 65 40 48 53]
 [12 16 60 88 82]
 [82 40  4 14 40]]
mean of all rows [45.2 46.6 49.8 51.6 36. ]
mean of all columns [40.2 30.4 46.6 58.8 53.2]
 replacing even number with -1 ............
row wise sorting matrix .............
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 21 -1 67 53]
 [43 65 77 77 83]]
column wise sorting matrix ...............
[[-1 -1 -1 77 83]
 [-1 -1 21 67 77]
 [-1 -1 43 53 65]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
row wise sum of matrix ..................
[157 163 159  -5  -5]
column wise sum of matrix ................
[ 39  83  73 141 133]
[4 3 4 3 3]
[4 3 4 3 3]


In [ ]:
# Question 2
import numpy as np
a=np.random.randint(1,90,25);
# or stock=np.random.randint(1,90,(5,5))
b=np.random.randint(1,90,25);
stock=a.reshape((5,5));
demand=b.reshape((5,5));
print("stocks:")
print(stock)
print("\n")
print("Demand:")
print(demand)
print("\n")

print("remaining stocks:")
rem_stock=stock-demand
print(rem_stock)
print("\n")

print("replacing negative stocks with 0..........")
s=np.where(rem_stock<0,0,rem_stock)
print(s)
print("\n")

print("shortage:")
shortage=np.sum(np.where(rem_stock<0,-1*rem_stock,0),axis=0)
print(shortage)
print("\n")

print("No shortage product:")
no_shortage=np.sum(np.where(rem_stock>=0,1,0))
print(no_shortage)
print("\n")

print("sorted remaining product:")
sorted_rem_product=np.sort(rem_stock,axis=1)
print(sorted_rem_product)

stocks
[[86 60 65 52 59]
 [49 39 53  9 82]
 [17 39 23 41 83]
 [79 72 74 31 66]
 [24 75 49 57 19]]


Demand
[[47 18 14 89 84]
 [72  3 62 17 50]
 [ 1 17 19 55 51]
 [25 44 53 62 83]
 [26 82 57 64 16]]


remaining stocks:
[[ 39  42  51 -37 -25]
 [-23  36  -9  -8  32]
 [ 16  22   4 -14  32]
 [ 54  28  21 -31 -17]
 [ -2  -7  -8  -7   3]]


[[39 42 51  0  0]
 [ 0 36  0  0 32]
 [16 22  4  0 32]
 [54 28 21  0  0]
 [ 0  0  0  0  3]]


shortage:
[25  7 17 97 42]


No shortage product:
13


sorted remaining product
[[-37 -25  39  42  51]
 [-23  -9  -8  32  36]
 [-14   4  16  22  32]
 [-31 -17  21  28  54]
 [ -8  -7  -7  -2   3]]


In [46]:
#*************** Pandas ******************
import pandas as pd
file_=pd.read_csv("student_data.csv",sep=",")
#print(file_)

# gives data of first x rows
print(file_.head(8))
# gives data from last x rows
print(file_.tail(5))



   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   
5            7          40            9              10   
6           10          40            4              11   
7            3          86            7               3   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
5                      0            